### ISSUE TITLE
Build.py is not Linux friendly

### ISSUE THREAD

**Issue by ghost** [u08614s/ShineClient#2]
upon looking at your Syntax of `build.py` you seem to make common use of the line
``` python
with open("scripts\\api-CodeEnablesSetter") as f:
```
however this syntax is highly unfriendly with a Linux environment, ( not suggesting a change, just pointing out a fact )
to change this you would need to modify the `open` line from what it is now to:
``` python
with open("scripts/api-CodeEnablesSetter") as f:
```
and in order to make any opened files executable like `build.sh` you would also need to execute
``` bash
sudo chmod +x filename.here
```

**Comment by u08614s** [comment]
thanks

**Comment by cedkeChat** [comment]
afterwards it's normal because the author uses a windows version for his client :)
